### ISSUE TITLE
Could this method be used with a twin design?

### ISSUE THREAD

**Issue by norwood12** [devlaming/mgreml#2]
I have trouble understanding how the tool achieves what is described in the paper, namely how are G and G* modeled and how it is ensured that they are not correlated. Aren't G and G* somewhat corresponding to variance components (random effects) in a mixed model? Relatedly, I was wondering if this method could be used with a study design with twins where the kinship (related to G/G* or not at all?) is determined by the zygosity of the twins. Apologies for the layman questions and thank you for the fantastic tool.

**Comment by devlaming** [comment]
Hi there,

Let **X** denote the _N_-by-_M_ genotype matrix (_N_ individuals, _M_ SNPs). If _G_ and _G_* would not be latent variables, one way to achieve independence between _G_ and _G_* (conditional on **X**), is to draw two vectors of random normal SNP effects, **b** and **b***, which are independent, and setting **G**=**Xb** and **G***=**Xb***. In that case, Var(**G**) is proportional to the genomic relatedness matrix (GRM, denoted by **A**), and so is Var(**G***). 

However, in practice, **G** and **G*** are not made explicit; they are latent variables, for which we only rely on their implied theoretical variance-covariance structure (i.e., Var(**G**)=**A**, Var(**G***)=**A**, and Cov(**G**,**G***)=**0**). Then, given our structural equation model (SEM), we trace how that shapes the phenotypic variance-covariance structure of mediator and outcome, and finally map that to a few quantities of potential interest to the applied researcher.

Re. twin studies: in theory, yes, **A** could be replaced by kinship matrix **K**, where the tool would then assume Var(**G**)=**K**, Var(**G***)=**K**, Cov(**G**,**G***)=**0**. Yet, currently MGREML does not support also modelling a shared-environment component **C**, which I guess is a considerable hurdle for application to data on strongly related individuals. Probably, for such an application, a tool like OpenMx would be more suitable: this allow you to specify and estimate a wide range of SEMs using the twin design.

Glad to hear your like the tool!

Best, Ronald

**Comment by norwood12** [comment]
Dear Ronald, Thank you so much for your generous explanation. Now I understand the concept. It's more than just liking the tool - I think it's mesmerizing and ingenious - I love it. I also thought about using OpenMX but I have trouble grasping how one could do mediation analysis while using a Mixed Effects Model. There have been a few similar questions online but either they did not receive any answer or the answer was too problem specific. Would you be aware of any general guide to mediation analysis with Mixed Effects models in OpenMX?

https://openmx.ssri.psu.edu/node/4516 (no answer)
https://gist.github.com/tbates/75a0cd7bc411fe6357504a2761b027ba (Mediation in OpenMX and why not use it - interesting but no content)
https://openmx.ssri.psu.edu/thread/3930 (too complicated but I admit I did not study it sufficiently)

Would there be a simple way in OpenMX to have an ACE (additive genetic, common environment, noise) variance component model for twins using just two traits - the dependent trait and the mediator trait and testing both if the A component is significant and whether there is mediation? I know these are some big questions... Any hint appreciated!

**Comment by devlaming** [comment]
Afraid I don't have much experience with OpenMx, so I can't help you there with the nitty-gritty details. But in as far as I do understand it, I guess it should be possible to formulate a SEM there with (1) an 'arrow' from your supposed mediator to your outcome of interest, (2) two latent genetic factors (analogous to G and G* in MGREML), (3) two unique environment factors (analogous to E and E*), and (4) two shared-environment factors (C and C*, so to speak). Good luck figuring out whether OpenMx can be of avail!

**Comment by norwood12** [comment]
Assuming that I manage to build the model in OpenMX, how do I test for mediation though if G and G* are latent variables? Should I just fix `b` (using MA-GREML connection names) to zero and compare the log-likelihood of such nested model to the full model? with a chi2 test?
